name: Update README ⭐
on: [push, workflow_dispatch]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 1641438
          leaderboardId: 107172
          sessionCookie: ${{ secrets.AOC_SESSION }}
          year: 2022
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stars